### ISSUE TITLE
Knowing the height of the text inserted

### ISSUE THREAD

**Issue by slevy85** [geongeorge/Canvas-Txt#13]
I have a use case where I need to insert some text at the end of a canvas, and then I need to adjust the height of the canvas so it fits the text.
I am not sure how to do this, but I thought I could use the value of `vheight` calculated at this line : https://github.com/geongeorge/Canvas-Txt/blob/a81297814e4e35e5245484c22d273f3c81c47984/src/index.js#L100

What do you think ? Maybe we could return it so we can use it :  
```
const { vHeight } = canvasTxt.drawText(ctx, txt, 0, 0, 200, 200)
```

**Comment by geongeorge** [comment]
Yeah, returning seems pretty okay. 
But is there something else we should return?
I intentionally left the return statement to be filled by something useful later.

You can actually use getTextHeight to fetch the height according to the font

**Comment by geongeorge** [comment]
Also just published v2.0.7 with your helpers in it 😄 🎊  https://www.npmjs.com/package/canvas-txt

**Comment by slevy85** [comment]
Thank you very much !
I think maybe we can return `charHeight` because it is a calculated value, anyway it doesn't cost to return it.

**Comment by geongeorge** [comment]
I kinda feel like that is a random thing to return. Maybe we should return other properties as well

**Comment by slevy85** [comment]
When there is just one line of text, `vheight` is equal `0`, so maybe we can return the real height like this :  
```
return { height : vheight + charHeight }
```
What do you think ?

**Comment by geongeorge** [comment]
looks okay but to get a perspective, can you share what you are gonna do with the height?

**Comment by slevy85** [comment]
I am not sure yet how I will do it but I want to adjust the height of the canvas to the height of the text.

```
const {height} = canvasTxt.drawText(ctx, possibleLongText, 0, 0, 1200, 1200)
canvs.height = height
```

**Comment by geongeorge** [comment]
Ah got it! That is honestly useful.

What do you think if we return the enclosing box for the text?
The width and height it took along with x,y of the first point.

**Comment by slevy85** [comment]
Yes i think it is a great idea.

**Comment by slevy85** [comment]
Hi @geongeorge , I am not sure how to have the enclosing box of the text, can I make a pull request to return only the height for now ?
I am sorry to ask this but I would need this feature soon.

Thank you.

**Comment by geongeorge** [comment]
Sure, will merge it ASAP

**Comment by slevy85** [comment]
Thank you very much
