### ISSUE TITLE
Feature Request: align justify

### ISSUE THREAD

**Issue by slevy85** [geongeorge/Canvas-Txt#18]
Hi @geongeorge ,

Is it possible to justify the text ? 
I know that canvas context doesn't support "align justify" because it doesn't support multi-line text, but since this package provides multi-line support, maybe it could be a nice feature to have.

What do you think we need to do to implement this ?

Thank you.

**Comment by geongeorge** [comment]
Should be possible, maybe even very easily.
I'm thinking:

1. Use the current center alignment feature
2. Measure the width of each line
3. Find the width of a single space
4. substitute spaces equally in between each word till the length is close enough to the max

At least that's what I think should be enough.
Might wanna look into how actual word processors handle this.

Just curious, what are you building?

**Comment by slevy85** [comment]
Thank you very much for your help.

I am just building a function to share an image with text from inside a PWA, the image and the text are dynamic and should be merged together.

**Comment by slevy85** [comment]
This pull request would close this issue.

**Comment by geongeorge** [comment]
Merged #19 :)
