### ISSUE TITLE
\n breaks, inconsistent line length

### ISSUE THREAD

**Issue by geongeorge** [geongeorge/Canvas-Txt#21]
Support for `\n` line breaks is already in here but 
this is only accounted for after lines are already split into arrays.
This ends up creating lines with a single word or few
![image](https://user-images.githubusercontent.com/29296982/86623608-7d5bc580-bfdf-11ea-8a24-3cc8b01f066f.png)

*Code*
```js
...
var txt =
  'Hello how are \n Lorem ipsum dolor sit ame\n Lorem ipsum dolor sit ame Lorem ipsum dolor sit ame'

canvasTxt.fontSize = 24
canvasTxt.fontWeight = '100'
canvasTxt.fontStyle = 'oblique'
canvasTxt.fontVariant = 'small-caps'
// canvasTxt.debug = true
canvasTxt.align = 'right'
canvasTxt.vAlign = 'middle'
...
```

**Comment by slevy85** [comment]
It looks normal to me, what would be the expected result ?

**Comment by geongeorge** [comment]
I think I made a mistake here. 

I was under the impression that the `\n` was before the word 'Ame'
and that the remaining lines came as a new line anyway even tho there's space in the 'ame' line
