### ISSUE TITLE
Issue when changing font size 

### ISSUE THREAD

**Issue by asadrazashah** [geongeorge/Canvas-Txt#24]
I have a method in my react class component that display text on canvas ,The properties passed to canvas text can be changed through state of the component everything works fine and I can change the font color ,text position ,but I when I change font size with text on top right or top left position the text dissapears from the canvas ,but shows up If I change it position other then top right and top left 

code I am using 

```js
  draw = (
    video: any,
    img: any,
    context: any,
    context2: any,
    width: any,
    height: any
  ) => {
    if (video.paused || video.ended) return false;
    context2.drawImage(video, 0, 0, width, height);
    context2.fillStyle = this.state.textColor;
    canvasTxt.fontSize = this.state.fontSize;
    canvasTxt.vAlign = this.state.vAlign;
    canvasTxt.align = this.state.align;
    canvasTxt.lineHeight = 20;
    canvasTxt.debug=true;
    canvasTxt.drawText(
      context2,
      this.state.text,
      30,
      30,
      width - 50,
      height - 50
    );
    let idata = context2.getImageData(0, 0, width, height);
    let that = this;
    context.putImageData(idata, 0, 0);
    setTimeout(function() {
      that.draw(video, img, context, context2, width, height);
    }, 0);
  };
```

**Comment by geongeorge** [comment]
Sorry been a bit busy with something.
@asadrazashah  Can you spin up a basic jsfiddle or codesandbox showing your issue?

**Comment by asadrazashah** [comment]
Hi geongeorge ,thanks for this wonderful package . It was an issue on my side .
Thank you for your time
