### ISSUE TITLE
Support for Node implementation

### ISSUE THREAD

**Issue by NielsKersic** [geongeorge/Canvas-Txt#28]
I love this package and would like to be able to use it in NodeJS applications as well. 
Currently, this does not seem to be possible, as it results in the following error:
`ReferenceError: window is not defined`

Are there any workarounds for this, or is this something that could be changed in a future update? 
Thanks!

**Comment by geongeorge** [comment]
Thanks for reaching out :)

Should be available in a couple of days (hopefully, if node-canvas does everything I want it to do)

https://github.com/geongeorge/Canvas-Txt/pull/29

**Comment by geongeorge** [comment]
@NielsKersic 

I've released a beta version with node support.
It'd be great if you can give it a test and let me know if everything alright.

### How to use

```bash
npm install canvas-txt@3.0.0-beta.1
```

```js
const canvasTxt = require("canvas-txt").default;

// Initialize canvas ...

canvasTxt.drawText(ctx, txt, 50, 50, 200, 200);
...
```

**Here's a demo repo:** https://github.com/geongeorge/canvas-txt-node-canvas-demo

**Comment by NielsKersic** [comment]
@geongeorge I'll run some tests tomorrow and let you know my findings. Might also create some Typescript definitions if I have time.

**Comment by geongeorge** [comment]
@NielsKersic  That will be Awesome! Make sure to fetch the latest pre-release: https://github.com/geongeorge/Canvas-Txt/releases

**Comment by geongeorge** [comment]
@NielsKersic any progress?

**Comment by NielsKersic** [comment]
Tested it out in my project and it works as expected! @geongeorge

**Comment by geongeorge** [comment]
Closing the issue

**Comment by NielsKersic** [comment]
@geongeorge TypeScript definitions can now be installed using `npm i @types/canvas-txt`.
https://www.npmjs.com/package/@types/canvas-txt
