### ISSUE TITLE
Support for `overflow` property

### ISSUE THREAD

**Issue by dimakuba** [geongeorge/Canvas-Txt#31]
Hi, 

i was looking for `overflow` property to clip overflowed content of an element's box, but found nothing 😕
it would be great to have such feature. Could you please consider?

Before `overflow`:
![image](https://user-images.githubusercontent.com/14943911/95570686-ee23db00-0a2f-11eb-81ff-55a9eec666f8.png)

After `overflow`:
![image](https://user-images.githubusercontent.com/14943911/95570726-ff6ce780-0a2f-11eb-9d4f-dc96c420e1cd.png)

**Comment by geongeorge** [comment]
This is honestly a great idea. Will see what I can do

**Comment by c4b4d4** [comment]
+1 for this 🙂

**Comment by selname** [comment]
I very need this function! 
When vAlign='top' the bottom should be trimmed as in DOM-div when overflow:hidden
But it's been 3 years already?!
