### ISSUE TITLE
[Question] Is there possible to get the text height dynamically if the text wrapped?

### ISSUE THREAD

**Issue by pizza0502** [geongeorge/Canvas-Txt#33]
Hi, wanna ask is there possible to get the text height dynamically if the text wrapped?

I've 2 different font of text stacking top bottom to each other, but I want the top text if it is goes to 2 lines, the bottom text position can be move to bottom. Is there a way to calculate this or just get the top text bounding box height so that I can get the value?

**Comment by mlbonniec** [comment]
Hi ? No news? @geongeorge

**Comment by thatsprettyfaroutman** [comment]
The `drawText` function returns the height of the drawn text
