### ISSUE TITLE
Vertical align center single line text

### ISSUE THREAD

**Issue by phanvanlinhpax** [geongeorge/Canvas-Txt#37]
I try your `jsfiddle` and I see that the single-line text doesn't center absolutely.

<img width="635" alt="center1" src="https://user-images.githubusercontent.com/75288773/103013588-ffc94900-456f-11eb-95e9-07a124dabc84.PNG">

Here is what I test center text on the canvas follows https://stackoverflow.com/questions/13771310/center-proportional-font-text-in-an-html5-canvas. Look like it centers vertical absolutely

<img width="622" alt="center2" src="https://user-images.githubusercontent.com/75288773/103013593-01930c80-4570-11eb-8906-dde9ee2b1506.PNG">

Sorry if I'm wrong.

**Comment by OlexandrPopov** [comment]
@phanvanlinhpax Try to play with [CanvasRenderingContext2D.textBaseline](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/textBaseline). `ideographic` and `bottom` values seem to align text properly. For example: 

```js
  const canvas = document.getElementById("typed-sig-canvas");
  const ctx = canvas.getContext('2d');

  ctx.fillStyle = 'black';
  ctx.textBaseline = 'bottom';
  canvasTxt.fontSize = 60;
  canvasTxt.lineHeight = 60;
  canvasTxt.debug = true;
  canvasTxt.drawText(ctx, typedSigText, 0, 0, 450, 180);
```

**Comment by geongeorge** [comment]
<img width="1118" alt="image" src="https://github.com/geongeorge/Canvas-Txt/assets/29296982/5ceb6821-35f9-40f6-929d-7054e8dde6c9">


Please try again. Feel free to create a new issue if persists
