### ISSUE TITLE
How to add options 

### ISSUE THREAD

**Issue by shinokada** [geongeorge/Canvas-Txt#38]
I like how you did in the project page adding handles for the text field, position slider, width slider, height slider, etc.

I am wondering how you did it.
Is there any source I can have a look at it?

![image](https://user-images.githubusercontent.com/147320/104993017-8127d480-5a65-11eb-9a53-2b18e3e7a114.png)

**Comment by geongeorge** [comment]
See the /docs folder. Sorry for the delayed response
