### ISSUE TITLE
Bug: If width is less than text-width

### ISSUE THREAD

**Issue by kumardot93** [geongeorge/Canvas-Txt#41]
If width is less than font-width then the one of the while loops never ends

**Comment by MCArth** [comment]
This can happen especially if there is a very high-width character e.g. ﷽ (displays like the following img on a canvas, which can easily be higher than your selected line width)

![image](https://github.com/geongeorge/Canvas-Txt/assets/26874892/1bcd8bb7-22d2-47c0-96cc-71c6485841e4)

**Comment by geongeorge** [comment]
This is now fixed
