### ISSUE TITLE
Space at the beginning of line not preserved

### ISSUE THREAD

**Issue by pedromcunha** [geongeorge/Canvas-Txt#45]
Hello, let me start by thanking the creator/mantainers of this little library it's great! However I'm running into one issue, I have some text that has some whitespaces in front of it. When I try to draw this text I'm noticing that the whitespace is trimmed out (only if it's not between actual characters in a line).

**Comment by pedromcunha** [comment]
I believe it's because of this:
https://github.com/geongeorge/Canvas-Txt/commit/90b76087be267cd84df9e2159811f58c508f557d

It would be nice to add a parameter to disable this functionality

**Comment by geongeorge** [comment]
Thanks for pointing this out @pedromcunha 
This was introduced to remove whitespaces after a new line split. I think you're right and keep the first and last whitespace if any by default (And maybe only trim a single whitespace whenever possible)
