### ISSUE TITLE
[Question]  How to check if text size will fill in the target canvas size or not ? 

### ISSUE THREAD

**Issue by CGS38** [geongeorge/Canvas-Txt#55]
Hello,
Thanks for this library. 
Is there any way to know if the text we want to write on the canvas will fit on the target canvas size given the selected parameters ? 
That would be very helpfull.
Thank you,

**Comment by Krastanov** [comment]
this seems related to your question https://github.com/geongeorge/Canvas-Txt/issues/33

**Comment by geongeorge** [comment]
So you can try something like this now:

```
const outputArray = splitText(ctx,text,{...})

if(outputArray.length === 1) {
 // will fit
 } else {
  // will not fit
 }
```
