### ISSUE TITLE
Squares instead text

### ISSUE THREAD

**Issue by Miduwu** [geongeorge/Canvas-Txt#58]
Hey yo! Someone knows why do i see squares instead normal text? I need help please i used as the example
![image](https://user-images.githubusercontent.com/83442808/130851246-d792cb84-8004-49fe-8a94-8b881083a85d.png)

**Comment by geongeorge** [comment]
Looks like an issue where the font is not loaded. @Miduwu  can you provide code samples?
Or create a codesandbox?

**Comment by rob52mc** [comment]
I have the same issue. I am using node.js on AWS Elastic Beanstalk.
Everything works find on my dev env on my laptop, but when I deploy to AWS all fonts are rendered as squares.
Current line of thinking is there are no fonts installed on the server.
