### ISSUE TITLE
nothing rendered on iOS11

### ISSUE THREAD

**Issue by badtant** [geongeorge/Canvas-Txt#62]
Hi,

If I don't specify lineHeight nothing gets rendered on iOS11.
From reading the code i guess the bug is somewhere in the getTextHeight function.

Thanks for a great canvas-helper!

**Comment by geongeorge** [comment]
I believe this is now solved. Checked on my iphone : https://github.com/geongeorge/Canvas-Txt/assets/29296982/1cadacae-652a-480f-b139-27c37dbcf3bf
