### ISSUE TITLE
Multiple Colors

### ISSUE THREAD

**Issue by Nineswiss** [geongeorge/Canvas-Txt#64]
Do you think there will be support for multiple colored words at any stage?

**Comment by Nineswiss** [comment]
I was actually able to get it to work
` //print all lines of text
    textarray.forEach(txtline => {
      txtline = txtline.trim()
      let wordArray = txtline.split(' ')
      let xPos=0
      wordArray.forEach(element => {
            ctx.fillStyle=randomColor()
            let width = ctx.measureText(element).width
            ctx.fillText(element, textanchor+xPos, txtY)
            xPos += width+(this.fontSize/4)
      });
      txtY += charHeight
    })`

**Comment by Nineswiss** [comment]
Actually the above breaks positioning of words when centered.

**Comment by Nineswiss** [comment]
This now seems to work:
`    //print all lines of text
    textarray.forEach(txtline => {
      txtline = txtline.trim()
      let wordArray = txtline.split(' ')
      let xPos=0
      const lineWidth = ctx.measureText(txtline).width
      // iterate over each word and set a color (or other values)
      wordArray.forEach(element => {
            ctx.fillStyle=randomColor()
            ctx.textAlign="left"
            let wordWidth = ctx.measureText(element).width
            if(this.align === 'left'){
                ctx.fillText(element, textanchor+xPos, txtY)
            }else if(this.align === 'center'){
                ctx.fillText(element, (textanchor+xPos)-lineWidth/2, txtY)
            }else{
                ctx.fillText(element, (textanchor-lineWidth)+xPos, txtY)
            }
            xPos += wordWidth+(this.fontSize/4)
      });

      txtY += charHeight

    })`

**Comment by Nineswiss** [comment]
Now working:
`textarray.forEach(txtline => {
      txtline = txtline.trim()
      let wordArray = txtline.split(' ')
      let xPos=0
      const lineWidth = ctx.measureText(txtline).width
      // iterate over each word and set a color (or other values)
      wordArray.forEach(element => {
            ctx.fillStyle=randomColor()
            ctx.textAlign="left"
            let wordWidth = ctx.measureText(element).width
            if(this.align === 'left'){
                ctx.fillText(element, textanchor+xPos, txtY)
            }else if(this.align === 'center'){
                ctx.fillText(element, (textanchor+xPos)-lineWidth/2, txtY)
            }else{
                ctx.fillText(element, (textanchor-lineWidth)+xPos, txtY)
            }
            xPos += wordWidth+(this.fontSize/4)
      });

      txtY += charHeight

    })`

**Comment by Nineswiss** [comment]
It now **_seems_** to be working:
` //print all lines of text
    textarray.forEach(txtline => {
      txtline = txtline.trim()
      let wordArray = txtline.split(' ')
      let xPos=0
      const lineWidth = ctx.measureText(txtline).width
      // iterate over each word and set a color (or other values)
      wordArray.forEach(element => {
            ctx.fillStyle=randomColor()
            ctx.textAlign="left"
            let wordWidth = ctx.measureText(element).width
            if(this.align === "left"){
                ctx.fillText(element, textanchor+xPos, txtY)
            }else if(this.align === "center"){
                ctx.fillText(element, (textanchor+xPos)-lineWidth/2, txtY)
            }else{
                ctx.fillText(element, (textanchor-lineWidth)+xPos, txtY)
            }
            xPos += wordWidth+(this.fontSize/4)
      });

      txtY += charHeight

    })`

**Comment by geongeorge** [comment]
You can do this now using `splitText` and rendering text on your own using v4. Check readme for docs
