### ISSUE TITLE
Fit text on N lines

### ISSUE THREAD

**Issue by PoeHaH** [geongeorge/Canvas-Txt#71]
Hi @geongeorge 

I know this library is probably not maintained anymore but I'm happy to pay for your time. 

In your opinion, would it be a lot of work to add an option to force the content on 1 line (or N lines)? So when the width exceeds 1 line, the font size becomes smaller so the text still fits on that one line.

**Comment by PoeHaH** [comment]
@geongeorge any feedback on this? :)

**Comment by geongeorge** [comment]
@PoeHaH Sorry for the delay. I was busy with a few other things. 

Currently, we recognize all line breaks and try to fit text accordingly. How would you suggest having a "fit to n lines" work with this? Should we ignore linebreaks? 

![image](https://user-images.githubusercontent.com/29296982/173568353-a2a1cfa7-cbc9-4f7d-89cc-8909f3747565.png)

**Comment by PoeHaH** [comment]
I mean, instead of the text going out of bounds (like the example image attached), it would decrease the font size so it stays inside the bounds. Is that possible? 
![image](https://user-images.githubusercontent.com/5845313/175761240-8e8a427c-e717-430e-a5b5-e9a21510412f.png)

**Comment by agenciadw** [comment]
How is this issue?

**Comment by geongeorge** [comment]
@PoeHaH @agenciadw This is something that makes total sense. I will try to fit this in the 4.0.0 release

**Comment by agenciadw** [comment]
> @PoeHaH @agenciadw This is something that makes total sense. I will try to fit this in the 4.0.0 release

Thank you.

**Comment by geongeorge** [comment]
I would love if you guys can provide some input here @PoeHaH @agenciadw 
https://github.com/geongeorge/Canvas-Txt/issues/77

**Comment by geongeorge** [comment]
You can now do this with `splitText` and only rendering that fit into your height

drawText returns the heigth now
