### ISSUE TITLE
Performance upgrades

### ISSUE THREAD

**Issue by jassmith** [geongeorge/Canvas-Txt#73]
Hi George! 

I am a big fan of your work; I really appreciate your contribution here. I wanted to use canvas-txt in another [project](https://grid.glideapps.com) I maintain however I found it to be too slow. I eventually forked and modified your library to the point of being basically unrecognizable, but made it better suited to the tasks I had at hand.

Anyway, I figured you might want to take some of the performance adaptations back into your library to make it much faster with large amounts of text. You can find the work here: https://github.com/glideapps/canvas-hypertxt

While I have every intention to maintain this library and keep it up to date as I need it for my own uses, I fully expect the vast majority of people are better served by canvas-txt unless they are performance sensitive or need to integrate into a larger rendering framework which already has text rendering functionality.

I'm still in the process of publishing and setting up project pages, if you decide to bring back any of the performance improvements Im happy to update the benchmarks.

**Comment by jassmith** [comment]
Some things you may wish to try to bring back:

- Smarter algorithm for finding breakpoints with fewer measure calls
- Avg char size memory to improve guesses in subsequent calls
- Reduced number of changes to the canvas state machine

**Comment by jassmith** [comment]
Sure, jason at heyglide dot com

**Comment by geongeorge** [comment]
Hi @jassmith, It would be amazing if you can provide some input here: https://github.com/geongeorge/Canvas-Txt/issues/77

**Comment by geongeorge** [comment]
New version published https://www.npmjs.com/package/canvas-txt 🎉

Thank you so much for all the feedback
