### ISSUE TITLE
Update the TypeScript Type definitions for canvas-txt 4.0

### ISSUE THREAD

**Issue by codeBelt** [geongeorge/Canvas-Txt#85]
The current TypeScript definition is for canvas-txt 3.0. Please update the type definitions to match the 4.0 version.

**Comment by geongeorge** [comment]
@codeBelt do you have `@types/canvas-txt` installed?

**Comment by pratheekbhandary** [comment]
@geongeorge seems like its not updated in a while. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/canvas-txt/index.d.ts

**Comment by geongeorge** [comment]
@pratheekbhandary Shouldn't this work out of the box if you simply uninstall @types/canvas-txt?
Because now the lib is now fully typed?

**Comment by pratheekbhandary** [comment]
Yea I noticed that. But for some reason, its not picking up the types for me, hence I had to manually declare it.

**Comment by pratheekbhandary** [comment]
Not an expert at this, but can the minification cause issues?
I don't see any types here.
![image](https://github.com/geongeorge/Canvas-Txt/assets/30550942/acd0fb57-eec0-45f4-a7f5-ab0fb465af7f)
![image](https://github.com/geongeorge/Canvas-Txt/assets/30550942/c13959f8-fa3f-42ab-8907-8b9b50f51eb7)
![image](https://github.com/geongeorge/Canvas-Txt/assets/30550942/1391bb0e-24ab-4e93-894c-5e47b29e5454)

**Comment by geongeorge** [comment]
Thanks @pratheekbhandary I believe this PR should resolve this https://github.com/geongeorge/Canvas-Txt/pull/86

Vite removes all the type definitions. I added a vite plugin named `vite-plugin-dts` but couldn't get it working. tsup seems like a good option

**Comment by geongeorge** [comment]
This is now fixed in v4.1.1 (I had to play around with a few versions to get it right. Finally did a minor version change. but feel free to update. nothing should break from 4.0)

<img width="607" alt="image" src="https://github.com/geongeorge/Canvas-Txt/assets/29296982/2bfd6e2a-5ece-496d-a8bc-669cd8068718">
