### ISSUE TITLE
Condition `splitPoint === 0` is always false in split-text.ts

### ISSUE THREAD

**Issue by jiakuan** [geongeorge/Canvas-Txt#88]
https://github.com/geongeorge/Canvas-Txt/blob/master/src/canvas-txt/lib/split-text.ts#L71

**Comment by jiakuan** [comment]
Created a pull request: https://github.com/geongeorge/Canvas-Txt/pull/89

**Comment by geongeorge** [comment]
@jiakuan Thanks, that makes a lot of sense
